@extends('layouts.gusa.basic')

@section('header-styles')
    @parent
    <link rel="stylesheet" type="text/css" href="css/gusa/mix.css">
@endsection

@section('description')
    Get America Standing is a campaign to educate on Active Working. How we started.
@endsection

@section('keywords')
    get-america-standing, active-working, productive-working, office-productivity, sit-stand, sit-stand-desk,
    standing-desk, height-adjustable-desk,variable-height-desk, healthy-office, treadmill-desk, desk-riser,
    desk-mount, home-office, health-and-safety, wellness
@endsection

@section('title')
    About Get America Standing. How We Started
@endsection


@section('content')
    <div class="contentarea">
        <div class="row-fluid">
            <div class="span_full module_cont module_text_area">

                <div class="aboutus-smallwidth">

                    @include('shared.trail')
                    <br/>

                    <h1>About Get America Standing</h1>

                    <br/>
                    Whilst visiting a charity in Sweden in 2013, Gavin Bradley noticed all the staff had access to Sit-Stand work
                    stations – and what’s more thought nothing of it.
                    <br/><br/>

                    Puzzled by this, Gavin decided to investigate the background to why Sweden (and indeed Scandinavia)
                    are all Sit-Standing at work and he soon realised that there was some stark scientific research
                    which has resulted in legislation mandating workers to have a right to height adjustable desks.
                    <br/><br/>

                    Gavin soon decided that America needed to become aware of the multiple health risks of sitting and
                    compelling benefits of converting sitting time to standing time whilst at work.
                    <br/><br/>

                    So Get America Standing was born.
                    <br/><br/>

                       <span class="gbs-expert">
                       <strong>
                           Our vision is that within 20 years more than 80 per cent of the workforce (four in five staff) will
                           convert between 2 – 4 hours of sitting time with standing daily at their desk.
                       </strong>
                       </span>
                    <br/><br/>

                    Please join in, follow us on social media (@getUSAstanding) and stay in contact.
                    <br/><br/><br/>


                  <!--

                    <div class="bluetitle redt">International Advisory Panel</div>

                    Get America Standing is proudly connected to Active Working CIC’s International Scientific
                    Advisory Panel (ISAP).
                    This panel consists of leading international scientific experts who have dedicated their
                    careers to building the evidence of sedentary behaviour, workplace design and public
                    health research. The panel provide their advice on a voluntary basis and
                    are not responsible for the messages in this campaign but
                    do lend their general support. The panel consists of:

                    


                    <br/><br/>


                    <div class="profpic">
                        <img src="img/getstanding/gb/patrons/stuart.jpg" alt="stuart biddle">
                    </div>
                    <br/>

                    <div class="profdesc">
                        <span class="profdesk-text"> <strong>Dr Stuart Biddle, PhD</strong><br/>
                       Professor of Active Living & Public Health, Victoria University, Australia. Chairman of Active Working CIC
                       International Scientific Advisory Panel (ISAP).</span><br/>

                        <div class="profq redt">
                            “I am personally delighted to support Get America Standing. It’s not a moment too soon.
                            I wish you every success in your campaign to help the British public make simple changes
                            to achieve significant health benefits generated by reducing sedentary time. Good luck!”
                        </div>

                    </div>
                    <div class="clear"></div>
                    <br/><br/>


                    <div class="profpic">
                        <img src="img/getstanding/gb/patrons/levine.jpg" alt="levine">
                    </div>
                    <br/>

                    <div class="profdesc">
                        <span class="profdesk-text"> <strong>Dr James Levine</strong><br/>
                           Professor of Medicine, Director Obesity Solutions, Mayo Clinic and Arizona State University
                        </span><br/>

                        <div class="profq redt">
                            “The international Get Standing campaigns play a vital role in improving the understanding of the problems
                            and solutions to combat sedentary behaviour in the workplace. I am honoured to be associated with such important work”
                        </div>

                    </div>
                    <div class="clear"></div>
                    <br/><br/>


                    <div class="profpic">
                        <img src="img/getstanding/gb/patrons/dunstan.jpg" alt="dunstan">
                    </div>
                    <br/>

                    <div class="profdesc">
                       <span class="profdesk-text"><strong>Dr David Dunstan</strong><br/>
                         Associate Professor & Head, Physical Activity Laboratory, Baker IDI, Melbourne Australia <br/>
                       </span>

                        <div class="profq redt">
                            “Prolonged sitting is the most underrated health threat of modern time. I am delighted to be
                            associated with an important international campaign which provides clear and simple
                            communication on the merits of reducing and breaking up sitting time in the workplace”.
                        </div>

                    </div>
                    <div class="clear"></div>
                    <br/><br/>


                    <div class="profpic">
                        <img src="img/getstanding/gb/patrons/buckley.jpg" alt="john buckley">
                    </div>
                    <br/>

                    <div class="profdesc">
                        <span class="profdesk-text"><strong>Dr John Buckley, PhD</strong><br/>
                           Reader of Applied Exercise Science in Health Chester.
                        </span>
                        <br/><br/>
                        John was lead author on the <a href="expert_statement">expert statement</a>
                        "The Sedentary Office: a growing case for change towards better health and productivity"
                        commissioned jointly by Public Health England with Active Working C.I.C. to provide guidance
                        for employers and staff working in an office environment.<br/>

                        <div class="profq redt">
                            "Get America Standing seems an excellent way to promote and educate the public about
                            the ills of sitting too much. It’s not just for inactive people either, as we know that
                            even for people who play sport and do exercise, if they spend a lot of their day sitting,
                            they too are putting their health at risk. Standing more is a health benefit for all."
                        </div>
                    </div>

                   <div class="clear"></div>
                   <br/><br/>


                    <div class="profpic">
                        <img src="img/getstanding/gb/patrons/ahedge.jpg" alt="alan hedge">
                    </div>

                    <br/>

                    <div class="profdesc">
                       <span class="profdesk-text"><strong>Professor Alan Hedge<br/></strong>
                          Professor of Ergonomics, Dept. Design and Environmental Analysis, Cornell University
                       </span>
                        <br/><br/>

                        Alan is the Environmental Design Representative for the International Ergonomics
                        Association and a Fellow of the Institute of Ergonomics and Human Factors (IEHF - UK).
                        He has conducted extensive research into Design and Workplace Ergonomics as they affect
                        health, comfort and productivity of workers - with heavy focus on workstation design
                        and computer ergonomics.

                        <div class="profq redt">
                            "For 20 years I have been a proponent of sit-stand workstations and reducing sitting
                            time in the workplace. It is wonderful to see the Get America Standing take off and develop
                            an education strategy that can bring real change to the workplace. It is high time for cultural
                            revolution to boost health and productivity in the workplace.”
                        </div>
                        <br/>

                    </div>
					
					-->
					

                    <div class="clear"></div>

                </div>



            </div>

        </div>
    </div>
@endsection
